'1111':
  API_KEY: '1111'
  BASE_URL: '111'
  MODEL_TYPE: '1111'
qwen-turbo:
  API_KEY: sk-dcc3b05091194b2e80d302fc0f58e82e
  BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v1
  MODEL_TYPE: qwen-turbo
yi-large:
  API_KEY: sk-dcc3b05091194b2e80d302fc0f58e82e
  BASE_URL: https://dashscope.aliyuncs.com/compatible-mode/v2
  MODEL_TYPE: yi-large
zzz:
  API_KEY: zzzz
  BASE_URL: zzz
  MODEL_TYPE: zzz
